---
title: "Homework: Linear Regression"
date: "due 2019-12-06 at 5:00 pm"
output: 
  html_document:
    css: hw-styles.css 
    includes:
      after_body: footer.html
---

## Goals 

This homework serves three goals 

- for you to use R locally
- build simple and multiple linear regression models
- make inference on regression coefficients

## Assignment

__Type:__ Individual

__Tasks:__

For this homework you will be using RStudio on a local machine, either your own personal computer or a school computer. Note that RStudio should be available on most computers across campus. 

All this time, we have been working with R Markdown files and knitting them to pdf documents on the Cloud. Whenever you click File > New File > R Markdown it gives you three different file types as a choice, HTML, PDF, and Word. I normally use HTML and teach with HTML. However, the reason we have been using PDF all this time was because Gradescope only accepts pdf file uploads!

For this homework we will be using HTML and one the homework is completed we will make it a pdf. The reason is because pdf files requires extra installation on your computer. However, if you are interested in making these installations such as installing TinyTex you are free to work with pdf. You can find instructions [here](https://bookdown.org/yihui/rmarkdown/installation.html) on how to download TinyTex. 

Make sure to watch the video on how to create R projects.



__Homework Questions__


1. OpenIntro 8.32 Beer and Blood Alcohol Content
2. OpenIntro 8.40 Cats, Part II
3. OpenIntro 9.14 Movie Returns, Part I
4. For this question you will be working with the [Pay for Play: Are Baseball Salaries Based on Performance? dataset](https://github.com/mdogucu/stats67-fa19-website/blob/master/hw/data/baseball-9192.csv). Right-click the button that says "Raw" on GitHub and select "Save Link As..." to download the data in `csv` format. Once downloaded, you will need to load the data set and save it as `baseball`. More information on the data can be found [here](http://jse.amstat.org/datasets/baseball.txt).

We are primarily interested in the association between the number of [doubles](https://en.wikipedia.org/wiki/Double_(baseball)) a player hits (`Doubles`) and their salary in thousands of dollars (`Salary`).

a. Make a scatter plot between the response and explanatory variable and describe the association you see.

b. Create a linear regression model that regresses `Salary` on `Doubles`. Print out the summary.

c. Interpret the two $\hat{\beta}$ values.

d. Create a linear regression model that regresses `Salary` on `Doubles`, as well as `BattingAvg`, `Runs`,`Walks`, `Strikeouts`, `Errors`, and `FreeAgent9192`.

e. Interpret the coefficient for `Doubles` again. How is this interpretation different than the one you gave in part (c)?

f. Add the residuals and predicted values to the data frame. Create residual plots and a qqplot. Comment on whether or not the conditions are met to use the model you found in part (d). 

g. Obtain a 95\% confidence interval for the coefficient on `Double`, and interpret it in the context of the problem.

h. Perform a hypothesis test on the coefficient for `Double` to test whether it has a linear relationship with `Salary`. State your hypotheses, draw your conclusion, provide evidence for the conclusion, and interpret your conclusion in the context of the problem.

 


__Scoring:__ 25 points

## Submission

In your project folder, you should see at least 4 things 

1. an R project
2. the dataset as a csv file
3. an R Markdown document
4. an HTML file that you get when you knit the R Markdown. 

Gradescope expects each answer to be on a separate page. So you will have to add page breaks to your document. Between each of your responses, add the following code `<p style="page-break-before: always">` to add page breaks. Add this between each response. That means this code should come after your response to Question 1a and before your response to Question 1b. See this [Rmd example](hw8-template-html.Rmd) file for further assistance. Note that HTML will not show page breaks. However, it will show the page breaks when you can save your file as a pdf.  To do that open the HTML file in Google Chrome (or any web browser) and try to print the document (not really) by clicking Ctrl + P (Windows) or Cmd + P (Mac). For Destination, instead of choosing a printer, choose _Save as PDF_ save the file. 

If you have been using pdf files all along, then you will have to use `\pagebreak` instead of the aforementioned code to add page breaks. See this [Rmd example](hw8-template-pdf.Rmd)

Upload the pdf file on Gradescope.

<br>
<br>
<br>