---
output: 
  pdf_document:
    template: template.tex
---
\begin{landscape}

\section {Review}

\begin{tabular}{|p{3cm}|p{1cm}|p{3cm}|p{3cm}|p{3cm}|p{3cm}|p{3.5cm}|}
  Question & point estimate & parameter of interest & expected value of the sampling distribution & variance of the sampling distribution & standard error & confidence interval \\ \hline
  single proportion & $\hat p$ & $p$ & $p$ & $\frac{p(1-p)}{n}$ & $\sqrt{\frac{\hat p (1-\hat p)}{n}}$ & $\hat p \pm z^*\sqrt{\frac{\hat p (1-\hat p)}{n}}$ \\ \hline
  difference of two proportion & $\hat p_1 - \hat p_2$ & $p_1 - p_2$ & $p_1 - p_2$ & $\frac{p_1 (1-p_1)}{n_1} + \frac{p_2 (1-p_2)}{n_2}$ & $\sqrt{\frac{\hat p_1 (1-\hat p_1)}{n_1} + \frac{\hat p_2 (1-\hat p_2)}{n_2}}$ & $(\hat p_1 - \hat p_2)\pm z^*\sqrt{\frac{\hat p_1 (1-\hat p_1)}{n_1} + \frac{\hat p_2 (1-\hat p_2)}{n_2}}$ \\ \hline
  single mean (dependent samples, paired data) & $\bar x$ & $\mu$ & $\mu$ & $\frac{\sigma^2}{n}$ &
  $\frac{s}{\sqrt{n}}$ & $\bar x\pm t^*_{df}\frac{s}{\sqrt{n}}$ \\ \hline
  difference of two means & $\bar x_1 - \bar x_2$ & $\mu_1 - \mu_2$ & $\mu_1 - \mu_2$ & $\frac{\sigma_1^2}{n_1}+\frac{\sigma_2^2}{n_2}$ &
  $\sqrt{\frac{s_1^2}{n_1} +\frac{s_2^2}{n_2}}$ & $(\bar x_1 - \bar x_2)\pm t^*_{df}\sqrt{\frac{s_1^2}{n_1} +\frac{s_2^2}{n_2}}$\\ \hline
  
\end{tabular}

\end{landscape}

\section{Simple Linear Regression}




y = mx+b

y = b0

Notation

Residuals 

Correlation

Guess the correlation game

R code for fitting a regression line
Ordinary Least Squares Regression

Interpretation R^2

Multiple regression with indicator variable

significance

Model comparison

broom
