---
output: 
  pdf_document:
    template: template.tex
---


__Decision Errors__

\begin{table}[H]
\begin{tabular}{ll|l|l|}
\cline{3-4}
 &  & \multicolumn{2}{c|}{\textbf{Decision}} \\ \cline{3-4} 
 &  & fail to reject $H_0$ & reject $H_0$ \\ \hline
\multicolumn{1}{|l|}{\multirow{2}{*}{\textbf{Truth}}} & $H_0$ true & Correct Decision & Type I Error ($\alpha$) \\ \cline{2-4} 
\multicolumn{1}{|l|}{} & $H_A$ true & Type II error ($\beta$) & Correct Decision \\ \hline
\end{tabular}
\end{table}

Example 
\vspace{8cm}

\section{Inference for a Difference of Two Proportions}

\subsection{Conditions}

1. The data are independent within two groups and between two groups.
2. Each group needs to have 10 successes and 10 failures.
\subsection{Confidence Interval}
\subsection{Hypothesis Testing}

If these conditions are met then

$(\hat p_1 - \hat p_2) \sim N(p_1 - p_2, \frac{p_1(1-p_1)}{n_1})+\frac{p_2(1-p_2)}{n_2})$

\newpage

Example: Does taking a college level science class change views on after life? Below are the responses from General Social Survey in 2018.


\begin{table}[H]
\begin{tabular}{|l|l|l|l|}
\hline
 &  & \multicolumn{2}{c|}{\textbf{Belief in Life After Death}} \\ \hline
 &  & Yes & No \\ \hline
\multirow{2}{*}{\textbf{College Science Course}} & Yes & 375 & 75 \\ \cline{2-4} 
 & No & 485 & 115 \\ \hline
\end{tabular}
\end{table}

Example: Calculate the 95\% confidence interval for the difference in proportion of belief in after life between those who have taken a college science course and those who have not in the population 



\newpage
Example: Evaluate whether taking a college level science class change views on after life with a hypothesis test.