---
title: "Midterm"
output: 
  html_document:
    css: midterm-styles.css 
    includes:
      after_body: footer.html
---

In order to get ready for the midterm, you should attempt at solving all the review questions. The review questions will be posted [here]() on 10/25. Note that these questions will not be graded. You are encouraged to study in groups for the midterm using these questions. The answer key for the review questions will not be provided until 11/1.

The midterm will have two parts: Part A and B. Both of these parts will be equally weighted. In other words each part is considered at 50% of your total midterm grade.

__Part A__

Part A of the midterm will be take-home. You will be assigned this project on RStudio Cloud on October 28th and will be expected to submit it by November 4th at 5:00 pm. Note that it will take you longer to complete Part A than a typical weekly homework. Plan accordingly and DO NOT leave it until the last day or even the weekend. This way you will have opportunity to come to our office hours to ask us any questions you may have. 

Part A will be provided to you on RStudio Cloud at this [project link](https://rstudio.cloud/spaces/29360/project/632693). Once you open the project, click on the `midterm.Rmd` link and then knit it. Read the whole set of questions in the knitted document before you attempt working on the `midterm.Rmd` file. 

You will have to submit it on Gradescope. No late submissions will be accepted. Do not leave the submission to the last minute. 

__Part B__

Part B of the midterm will be in class on Nov 4th at the usual lecture time and location. During this exam you will be provided a [cheat sheet](cheatsheet.pdf) with the midterm. You can read the policies [here](policies.pdf). You are encouraged to read the policies before coming to the midterm.

<br>
<br>
<br>
